import './js/movieCardModal';
import './js/myLibraryLocalStorage';
import './js/pageTheme';
// import './js/loader';
// import './js/goTopBtn';
// import './js/authorization';
// import './js/loader';
import './js/authorization/functions';
// import './js/authorization/firebaseConfig';
import './js/teamModal';
import './js/videoModal';
import './sass/index.scss';
